pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Hyprland
import Quickshell.Io

import qs.modules.common
import qs.modules.common.functions

/**
 * Configs Hyprland directly without external python scripts
 */
Singleton {
    id: root

    signal reloaded()

    readonly property string shellOverridesPath: FileUtils.trimFileProtocol(`${Directories.config}/hypr/hyprland/shellOverrides/main.lua`)
    readonly property string headerComment: "-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL AND FOLLOWS STRICT RULES\n-- In other words, I ain't writing a lua parser for this, so please be a good boi/girl/whatever\n"

    FileView {
        id: overridesFileView
        path: Qt.resolvedUrl("file://" + root.shellOverridesPath)

        onLoadFailed: error => {
            if (error == FileViewError.FileNotFound) {
                overridesFileView.setText(root.headerComment);
            }
        }
    }

    function formatValue(value) {
        if (value === "true" || value === "false" || value === true || value === false)
            return String(value);
        const strVal = String(value).trim();
        const num = Number(strVal);
        if (!isNaN(num) && strVal !== "")
            return strVal;
        return `"${value}"`;
    }

    function buildNestedStructure(keyParts, value) {
        if (keyParts.length === 1)
            return `${keyParts[0]}=${root.formatValue(value)}`;
        return `${keyParts[0]}={${root.buildNestedStructure(keyParts.slice(1), value)}}`;
    }

    function generateConfigLine(key, value) {
        const keyParts = key.split(":");
        return `hl.config({${root.buildNestedStructure(keyParts, value)}})`;
    }

    function makeKeyRegex(key) {
        const keyParts = key.split(":");
        const escapedParts = keyParts.map(p => p.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
        if (escapedParts.length > 1) {
            const nestedPattern = escapedParts.map(p => `\\s*${p}\\s*=`).join("\\{");
            return new RegExp(`^\\s*hl\\.config\\(\\{\\s*${nestedPattern}`);
        }
        return new RegExp(`^\\s*hl\\.config\\(\\{\\s*${escapedParts[0]}\\s*=`);
    }

    function editConfig(setEntries, resetKeys) {
        let text = overridesFileView.text();
        if (!text || text.trim() === "") {
            text = root.headerComment;
        }

        const lines = text.split(/\r?\n/);
        while (lines.length > 0 && lines[lines.length - 1] === "") {
            lines.pop();
        }

        const setDict = {};
        const resetSet = new Set(resetKeys || []);

        if (setEntries) {
            for (let k in setEntries) {
                const val = setEntries[k];
                if (val === "[[EMPTY]]") {
                    resetSet.add(k);
                } else {
                    setDict[k] = val;
                }
            }
        }

        const patterns = {};
        for (let k in setDict) patterns[k] = root.makeKeyRegex(k);
        for (let k of resetSet) patterns[k] = root.makeKeyRegex(k);

        const newLines = [];
        const foundKeys = new Set();

        for (let i = 0; i < lines.length; i++) {
            const line = lines[i];
            let matched = false;

            for (let k of resetSet) {
                if (patterns[k] && patterns[k].test(line)) {
                    matched = true;
                    break;
                }
            }
            if (matched) continue;

            for (let k in setDict) {
                if (patterns[k] && patterns[k].test(line)) {
                    newLines.push(root.generateConfigLine(k, setDict[k]));
                    foundKeys.add(k);
                    matched = true;
                    break;
                }
            }
            if (matched) continue;

            newLines.push(line);
        }

        for (let k in setDict) {
            if (!foundKeys.has(k)) {
                newLines.push(root.generateConfigLine(k, setDict[k]));
            }
        }

        let output = newLines.join("\n") + "\n";
        overridesFileView.setText(output);
    }

    function set(key, value) {
        const entries = {};
        entries[key] = value;
        root.editConfig(entries, []);
    }

    function setMany(entries) {
        root.editConfig(entries, []);
    }

    function reset(key) {
        root.editConfig({}, [key]);
    }

    function resetMany(keys) {
        root.editConfig({}, keys);
    }

    Connections {
        target: Hyprland

        function onRawEvent(event) {
            if (event.name == "configreloaded") {
                root.reloaded();
            }
        }
    }
}
